Inherit `Include` and `Exclude` paths from RuboCop
Shopify/ruby-style-guide pull request #250
Opened 2021-04-01 21:00 UTC by andyw8

This was originally intended to prevent CI from inadvertently finding a `.rubocop.yml` in `node_modules` and applying that config.

The scope has expanded to provide a better out-of-the-box experience. When a user of the gem configures an `Include` or `Exclude`, this will now be merged with RuboCop's default configuration. Previously, this would have completely replaced RuboCop's defaults. 

This PR also removes the Rails-specific exclusion of `db/schema.rb` which should now be handled in the repo's own configuration.

2021-04-01 21:27 UTC, andyw8 commented
Dupe of https://github.com/Shopify/ruby-style-guide/pull/231

2021-04-01 21:38 UTC, rafaelfranca approved these changes
Keeping the Rubocop defaults makes sense to me. I know those are application specific, but so it is db/schema.rb, so I think we would be better by using the same defaults as rubocop.

2021-04-04 15:47 UTC, volmer requested changes
I 💯 agree that we should be excluding these directories, but that should be done by inheriting the default exclude files from RuboCop directly, just like we do currently with `Include` (which allows us to include files such as `Gemfile`, `Rakefile`, etc). 

We used to inherit `Exclude` in the past, until we created our own list in  #36. That's the point where we stopped inheriting from RuboCop as our list overrides theirs.

In order to add more patterns to `Exclude` as well as still inheriting the original list, we must use `inherit_mode`: https://docs.rubocop.org/rubocop/configuration.html#merging-arrays-using-inherit_mode

However, I am not sure if there is even a point in doing so. Note that all apps currently using our gem probably have their own `Exclude` lists, which completely overrides our own. That's the current behaviour. In other words, our exclusion of `db/schema.rb` is likely useless, as well as this new list in this PR.

Solving this is also not as simple as enabling `inherit_mode`, as this might arguably break the RuboCop config of current apps.

My opinion so far is that we should not define a `Exclude` config. RuboCop's defaults are good enough, and apps that want to use can simple set their own `inherit_mode`.

2021-04-05 13:38 UTC, andyw8 commented
Thanks @volmer, good points there.

So although we may not be able to solve this for existing apps, could we improve the situation for new apps by changing the README instructions to:

```
inherit_mode:
  merge:
    - Exclude
inherit_gem:
  rubocop-shopify: rubocop.yml
```

2021-04-05 14:05 UTC, volmer commented
We could either give users instructions on inheritance mode or be opinionated about enabling the merging of those configs. But that opens up another question, which is: why would we enable (or suggest to enable) the merging of `Exclude` but not `Include` and other settings? RuboCop's default is the complete override for all settings in all cops when a custom config is defined. For sure nothing prevents us to consider `Include`/`Exclude` special cases; I am just pushing us to be intentional with our own decisions.

2021-04-05 19:25 UTC, andyw8 commented
Update as per Slack with @volmer. Sharing for discussion, but I have not tested yet so should not be merged.

2021-04-05 19:29 UTC, andyw8 commented
(I think an explanation should also be added to the README).

2021-04-05 20:27 UTC, volmer approved these changes
Looks good to me! 👍🏼

2021-04-05 20:40 UTC, rafaelfranca approved these changes

2021-04-06 00:16 UTC, merged